name: Deploy Project

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # uncomment both tokens for assignment 2-4

      HEROKU_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_TEST }}

    steps:
      # checkout repository code
      - uses: actions/checkout@v1

      # deploy code
      - run: heroku git:remote -a $HEROKU_APP_NAME
      - run: git push heroku HEAD:refs/heads/master


